#!/bin/sh

# VARS
############################################
DATE=$(date +%F_%R)
DIR="/home/${USER}/encrypted_files"
TXT="${DIR}/CYPHER_MESSAGE_${DATE}.txt"
TXT2="${DIR}/DECRYPTED_MESSAGE_${DATE}.txt"
############################################

mkdir -p ${DIR}

clear

echo ""
echo "=========================================="
echo ""
echo "             ENCRYPTINATOR"
echo ""
echo "=========================================="
sleep .5

clear

echo ""
echo "                 NOTE:"
echo ""
echo "If you wish to share your message with"
echo "others, you must share the encryption"
echo "password with them, as well."
echo ""
echo "Make sure you commit your password to"
echo "memory!"
echo ""

sleep 3

clear

while [ ANSWER != "0" ]  
do 

echo "---------------------------------"
echo ""
echo "               MENU"
echo ""
echo "---------------------------------"
echo ""
echo ""
echo "Select from the following options: "
echo ""

echo "1) Encrypt a message"
echo "2) Decrypt a message"
echo "3) DELETE ALL FILES IN ${DIR}"
echo "4) Quit"
echo ""

read -p "Selection: " ANSWER
clear

    case $ANSWER in
      1) read -p "Enter your message here:  " MESSAGE
         echo ""
         echo "${MESSAGE}" | openssl enc -aes-256-cbc -a -A -salt -pbkdf2  -iter 250000 -md sha512| tee ${TXT}
         echo ""
         sleep .5
         echo ""
         echo "Creating checksum for ${TXT}..."
         echo ""
         sleep .5
         
         sha256sum ${TXT} | tee ${TXT}_sha256sum.txt
         echo ""
         sleep .5
         ;;
      2) read -p "Enter the location and full name of your message to be decrypted here (e.g. /home/$USER/file.txt): " DECRYPT
         echo ""
         read -p "Enter the location of the full name of your checksum to be validated here (e.g. /home/$USER/file_sha256sum.txt): " SUM
         echo "" 
                 
         if [ $(sha256sum -c ${SUM} | awk '{print $2}') = 'OK' ]
         
         then
         
           echo ""
           echo "Valid file!"
           echo ""
           sleep .5           
           echo "Decrypting file now..."
           echo ""
           sleep .5
           cat "${DECRYPT}" | openssl enc -aes-256-cbc -d -a -A -salt -pbkdf2 -iter 250000 -md sha512 | tee ${TXT2} 
                     
         else   
                
           echo ""
           echo "WARNING!! FILE CHECKSUM MISMATCH!! PROCEED WITH CAUTION!!"
           echo ""
           
           while true
           do
           read -p "Would you like to proceed anyway? Y/N:  " PROCEED
             case ${PROCEED} in
               [Yy]* ) echo ""
                       echo "Decrypting without validation now..."
                       echo ""
                       sleep .5               
                       cat "${DECRYPT}" | openssl enc -aes-256-cbc -d -a -A -salt -pbkdf2 -iter 250000 -md sha512 | tee ${TXT2} 
               
                       echo ""
                       sleep .5 
                       exit
                       ;;               
                [Nn]* ) exit;;
                * ) echo "Please answer yes or no";;
             esac
           done
           fi
         ;;
         
      3) echo "WARNING!! THIS WILL DELETE ALL FILES FROM ${DIR}!"
         echo ""
         sleep .5
         while true
         do
         read -p "Are you sure? Y/N:  " KILL
           case ${KILL} in

             [Yy]* ) echo ""
                     echo "DELETING ALL FILES FROM ${DIR} NOW..."
                     echo ""
                     sleep .5
                     rm -rf ${DIR}/*
                     exit
                     ;;

             [Nn]* ) echo ""
                     echo "Exiting and no files will be deleted..."
                     echo ""
                     sleep .5
                     exit 
                     ;;

                 * ) echo ""
                     echo "Please answer yes or no";;
           esac
         done
         ;;
      4) break ;;
    esac
    echo ""
    echo "Press RETURN for MENU"
    echo ""
    read key
done
exit 0
